{
  "formatVersion": "1.1",
  "component": {
    "group": "moe.tlaster",
    "module": "Zoomable",
    "version": "0.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "Zoomable-0.6.3.aar",
          "url": "Zoomable-0.6.3.aar",
          "size": 69207,
          "sha512": "ad754177016c512b67f89ba155e74fd3cdf5905838cff5195004dbda89d4e574b364cf7bc1df0e7cee23dd2bf4a1eba10fe67eb99ffa40652d37640807250ae0",
          "sha256": "83a196dd06a83d1f299e345f74121d529e0e957a05a4224f7e6d1df8509ea92b",
          "sha1": "180b991d31bdf50508c031206116e61127adf401",
          "md5": "832c871a85b762cec2a21886ab96084c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "Zoomable-0.6.3.aar",
          "url": "Zoomable-0.6.3.aar",
          "size": 69207,
          "sha512": "ad754177016c512b67f89ba155e74fd3cdf5905838cff5195004dbda89d4e574b364cf7bc1df0e7cee23dd2bf4a1eba10fe67eb99ffa40652d37640807250ae0",
          "sha256": "83a196dd06a83d1f299e345f74121d529e0e957a05a4224f7e6d1df8509ea92b",
          "sha1": "180b991d31bdf50508c031206116e61127adf401",
          "md5": "832c871a85b762cec2a21886ab96084c"
        }
      ]
    }
  ]
}
